services:
  go-quick-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  mongo_data: